.TH WORDCOUNT 3 "September 2026" "BSDSF24M043-OS-A01" "Library Functions"
.SH NAME
wordCount \- count the number of words in a string
.SH SYNOPSIS
.B int wordCount(const char *str);
.SH DESCRIPTION
The
.B wordCount()
function counts and returns the number of words contained in the given string.
Words are separated by whitespace characters such as spaces, tabs, and newlines.
.SH AUTHOR
Ahmad Muavia <m.ahmad.mm2466@gmail.com>
